spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
  jpa:
    hibernate.ddl-auto: update
  h2.console.enabled: true
jwt:
  secret: change-me
  ttlHours: 6
server.port: 8080
---
spring:
  config.activate.on-profile: redis
  data.redis.host: localhost
  data.redis.port: 6379
---
spring:
  config.activate.on-profile: mongo
  data.mongodb.uri: mongodb://localhost:27017/cqrs
